source "https://rubygems.org"

gem 'cucumber', '~> 3.1.0'
gem 'rspec', '~> 3.7.0'
gem 'capybara', '~> 3.1'
gem 'selenium-webdriver', '~> 3.12'
gem 'site_prism',
    git: 'https://github.com/bukalapak/site_prism.git',
    branch: 'bukalapak_dev'